### ISSUE TITLE
The backslash character \ is added before \ and " in the messages.

### ISSUE THREAD

**Issue by ira-gordin-sap** [SAP/vscode-logging#14]
Code: 
getLogger().info('Congratulations, your extension "vscode-wing-odata-service-tools" is now active!');
Log entry:
{
  "label": "vscode-wing-odata-service-tools",
  "level": "info",
  "message": "Congratulations, your extension \"vscode-wing-odata-service-tools\" is now active!",
  "source": {
    "function": "activate",
    "location": "c:\\git\\vscode-wing-odata-service-tools\\out\\src\\extension.js:15:34"
  },
  "time": "2020-01-20 09:08:57.923Z"
}

**Comment by bd82** [comment]
This is JSON string escape rules.
- https://www.json.org/json-en.html
