### ISSUE TITLE
 logger.info() outputs strange message when receives 2 parameters. Should concatenate.

### ISSUE THREAD

**Issue by ira-gordin-sap** [SAP/vscode-logging#17]
Code:
this.logger.info("The user selection:",  `"${userSelection.label}".`);
Log entry:
{
  "0": "\"",
  "1": "S",
  "2": "A",
  "3": "P",
  "4": " ",
  "5": "A",
  "6": "P",
  "7": "I",
  "8": " ",
  "9": "B",
  "10": "u",
  "11": "s",
  "12": "i",
  "13": "n",
  "14": "e",
  "15": "s",
  "16": "s",
  "17": " ",
  "18": "H",
  "19": "u",
  "20": "b",
  "21": "\"",
  "22": ".",
  "label": "vscode-wing-odata-service-tools",
  "level": "info",
  "message": "The user selection:",
  "source": {
    "function": "ConsumeSAPServicesCommand.<anonymous>",
    "location": "c:\\git\\vscode-wing-odata-service-tools\\out\\src\\commands\\consumeSAPServicesCommand.js:41:33"
  },
  "time": "2020-01-20 10:02:01.293Z"
}

**Comment by bd82** [comment]
This feature does not exist in our API.
